name: Release Droid - Print Quick Checksum

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven skipping tests
        run: mvn --batch-mode --file pom.xml clean verify -DskipTests
      - name: Print checksum
        run: echo 'checksum_start==';find hadoop-etl-dist/target -name *.jar -exec sha256sum "{}" + | xargs;echo '==checksum_end'

